name = "telegram-calendar"
main = "dist/index.js"
compatibility_date = "2023-10-07"
compatibility_flags = ["nodejs_compat"]
account_id = "e023ec3576222c6a7b6cdf933de3d915"

[observability.logs]
enabled = true
head_sampling_rate = 0.1

[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "telegram-calendar"
database_id = "c69ea172-cc34-492c-af2c-ad1008927371"

[[kv_namespaces]]
binding = "KV" # i.e. available in your Worker on env.KV
id = "31099b01f2344641acec6e963e487b87"
preview_id = "e31e41f2c1d248af99e5c250cc318bcb"

[[r2_buckets]]
binding = "IMAGES" # i.e. available in your Worker on env.IMAGES
bucket_name = "images"