name = "marketplace-worker"
main = "apps/worker/src/index.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]
account_id = "e023ec3576222c6a7b6cdf933de3d915"

[observability]
enabled = true

# For local development, these resources are simulated by wrangler --local
[[d1_databases]]
binding = "DB"
database_name = "marketplace-db"
database_id = "097fa36e-2af3-48fe-a777-c19706920a8d"

[[kv_namespaces]]
binding = "CACHE_KV"
id = "f2cc0627e45b4d08af9cd7cdccf9fa2d"
preview_id = "f2cc0627e45b4d08af9cd7cdccf9fa2d"

[[kv_namespaces]]
binding = "SESSION_KV"
id = "300b88f82e23404fb97127c316cb6c87"
preview_id = "300b88f82e23404fb97127c316cb6c87"

[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "marketplace-images"